#!/bin/bash

####
#author: Raghunath
#date: 21-05
#this script is all about the aws resource untilization tracker

set -x

echo "print 1 to 100"

for i in {1..100} do
if ['expr "$i%2' == 0]
then
echo "print below are the even numbers"
